<?php

namespace App\Http\Controllers\SupportTeam;

use App\Helpers\Qs;
use App\Http\Controllers\Controller;
use App\Models\MyClass;
use App\Repositories\ExamRepo;
use App\Repositories\MarkRepo;
use App\Repositories\MyClassRepo;
use App\Repositories\StudentRepo;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ClassMasterController extends Controller
{
    protected $my_class, $exam, $mark, $student;

    public function __construct(MyClassRepo $my_class, ExamRepo $exam, MarkRepo $mark, StudentRepo $student)
    {
        $this->my_class = $my_class;
        $this->exam = $exam;
        $this->mark = $mark;
        $this->student = $student;
    }

    public function index(Request $req)
    {
        $userId = Auth::id();
        $formMasterClasses = MyClass::where('teacher_id', $userId)->with('section')->get();
        if ($formMasterClasses->isEmpty()) {
            return view('pages.support_team.class_master.dashboard', [
                'form_master_classes' => collect(),
                'my_class' => null,
                'sections' => collect(),
                'students' => collect(),
            'term' => null,
                'class_id' => null,
                'section_id' => null,
                'year' => Qs::getSetting('current_session'),
                'grand_totals' => [],
            ])->with('pop_error', __('You are not assigned as Form Master to any class.'));
        }

        $year = Qs::getSetting('current_session');
        $class_id = $req->get('class_id', $formMasterClasses->first()->id);
        $section_id = $req->get('section_id');
        $term = $req->get('term', 1);

        $my_class = MyClass::find($class_id);
        if (!$my_class || (int) $my_class->teacher_id !== (int) $userId) {
            $my_class = $formMasterClasses->first();
            $class_id = $my_class->id;
        }

        $sections = $this->my_class->getAllSections()->where('my_class_id', $class_id);
        if ($section_id && $sections->contains('id', $section_id)) {
            // keep section_id
        } else {
            $section_id = $sections->first() ? $sections->first()->id : null;
        }

        $terms = [1 => __('Term 1'), 2 => __('Term 2')];
        $term = in_array((int) $term, [1, 2], true) ? (int) $term : 1;

        $students = collect();
        $grand_totals = [];
        $exr = collect();
        if ($class_id && $section_id) {
            $students = $this->student->getRecord([
                'my_class_id' => $class_id,
                'section_id' => $section_id,
                'session' => $year,
            ])->get()->sortBy('user.name');
            foreach ($students as $st) {
                $grand_totals[$st->user_id] = $this->mark->getGrandTotal($term, $st->user_id, $class_id, $year);
            }
            $exr = $this->exam->getRecord([
                'term' => $term,
                'my_class_id' => $class_id,
                'section_id' => $section_id,
                'year' => $year,
            ])->get()->keyBy('student_id');
        }

        return view('pages.support_team.class_master.dashboard', [
            'form_master_classes' => $formMasterClasses,
            'my_class' => $my_class,
            'sections' => $sections,
            'students' => $students,
            'terms' => $terms,
            'term' => $term,
            'class_id' => $class_id,
            'section_id' => $section_id,
            'year' => $year,
            'grand_totals' => $grand_totals,
            'exam_records' => $exr,
        ]);
    }

    public function generateRanks(Request $req)
    {
        $userId = Auth::id();
        $class_id = (int) $req->class_id;
        $section_id = (int) $req->section_id;
        $term = (int) $req->term;
        $mc = MyClass::find($class_id);
        if (!$mc || (int) $mc->teacher_id !== $userId) {
            return back()->with('pop_error', __('msg.denied'));
        }
        if (!in_array($term, [1, 2], true)) {
            return back()->with('pop_error', __('Invalid term.'));
        }
        $year = Qs::getSetting('current_session');
        $this->mark->updateClassPositions($term, $class_id, $section_id, $year);
        return redirect()->route('class_master.dashboard', ['class_id' => $class_id, 'section_id' => $section_id, 'term' => $term])
            ->with('flash_success', __('Class ranks generated by grand total.'));
    }
}
